<?php

/*
 * Implementation of hook_form_BASE_FORM_ID_alter()
 */
function authoronlyfield_form_node_form_alter(&$form, $form_state, $form_id) {
  global $user;
  $uid = $user->uid;
  $node_uid = $form['uid']['#value'];
  if ($uid != $node_uid) {
    // strip any author-only field instances on this node.
    $author_only_instance_ids = _authoronlyfield_get_authoronlyfield_field_instance_ids();
    foreach($form_state['field'] as $field_name => $field) {
      $instance_id = $field[LANGUAGE_NONE]['instance']['id'];
      if (in_array($instance_id, $author_only_instance_ids)) {
        // This field instance is flagged as author-only, so remove it from the edit form.
        unset($form[$field_name]);
      }
    }
  }
}

/* Implementation of hook_menu()
 */
function authoronlyfield_menu() {
  $items['admin/structure/authoronlyfield'] = array(
    'title' => 'Author-only Fields',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_authoronlyfield_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'form/settings.php',
  );
  return $items;
}

function _authoronlyfield_get_authoronlyfield_field_instance_ids() {
  $setting = variable_get('authoronlyfield_field_instances', []);
  $positive = array_filter($setting, function ($value) {
    return $value > 0;
  });
  return array_keys($positive);
}